# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-06 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(default='', max_length=30, verbose_name='\u5730\u5740'),
        ),
    ]
